### ISSUE TITLE
Crash Error: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered Exit Code: -1

### ISSUE THREAD

**Issue by Baggytrousers27** [Snownee/LavaClearView#1]
### Mod loader

Forge

### Minecraft version

1.18

### Mod version

3.0.0

### Modloader version

38.0.14

### If bug:

- [X] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/21HqGqPC

### Issue description

Crash shortly after minecraft window opens.
Lava clear view by itself.

**Comment by Snownee** [comment]
Thank you!

**Comment by Baggytrousers27** [comment]
¦D
