### ISSUE TITLE
Game crashes at start up when paired up with Optifabric and Optifine

### ISSUE THREAD

**Issue by 23SRLITheGamer** [Snownee/LavaClearView#3]
### Mod loader

Fabric

### Minecraft version

1.18.2

### Mod version

4.0.1

### Modloader version

Fabric 1.18.2-0.14.4

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### If bug: The latest.log file

https://pastebin.com/EbQ1DZd1

### Issue description

The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_758 failed
Exit Code: -1

[Crash Report](https://pastebin.com/Ea3DigNs)

I've removed every mod and when it is with Optifabric and Optifine, it crashes.

**Comment by erkamtb** [comment]
yeah same is there any mod that remowes lava fog? or lava texture

**Comment by Snownee** [comment]
consider using Tweakeroo
