### ISSUE TITLE
Is this clientside only?

### ISSUE THREAD

**Issue by katubug** [Snownee/LavaClearView#8]
### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

7.0.0

### Modloader version

Forge 47.2.17

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Sorry to make a whole issue for this, but comments were disabled. Is this mod client-sided only? Or also required on a server? Thanks!

**Comment by Snownee** [comment]
for Forge, probably yes
